name: labees
description: labees mobile app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg:
  persistent_bottom_nav_bar: ^5.0.2
  carousel_slider: ^4.2.1
  cached_network_image: ^3.3.1
  syncfusion_flutter_sliders:
  flutter_rating_bar: ^4.0.1
  sticky_headers: ^0.3.0+2
  google_maps_flutter: ^2.3.0
  geocoding: ^2.1.1
  provider: ^6.1.1
  flutter_easyloading: ^3.0.5
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.0
  html: ^0.15.0
  shimmer: ^3.0.0
  badges: ^3.1.0
  http:
  intl: 0.18.1
  image_picker: ^1.0.1
  file_picker: ^5.2.9
  algolia: ^1.1.2
  photo_view: ^0.14.0
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.16.0
  permission_handler: ^10.4.0
  flutter_local_notifications: ^16.3.0
  awesome_snackbar_content: ^0.1.3
  hyperpay_plugin: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Libre Baskerville
      fonts:
        - asset: assets/fonts/LibreBaskerville-Bold.ttf
          weight: 700
        - asset: assets/fonts/LibreBaskerville-Italic.ttf
          style: italic
        - asset: assets/fonts/LibreBaskerville-Regular.ttf
          weight: 400
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-BlackItalic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-ExtraBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-ExtraLightItalic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-MediumItalic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-SemiBoldItalic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ThinItalic.ttf
          style: italic
